package org.mouthaan.netify.service.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.mouthaan.netify.domain.model.Gender;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * The class Actor Data Transfer Object.
 * Constructors, getters and setters are generated by Lombok
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ActorDto {
    private Integer id;

    @NotNull(message = "actor.Dto.name.notnull")
    @Size(min = 3, max = 255, message = "actor.Dto.name.size")
    private String name;

    @NotNull(message = "actor.Dto.gender.notnull")
    private Gender gender;

    @Override
    public boolean equals(Object o) {
        ActorDto actorDto;
        if (o.getClass() == this.getClass()) {
            actorDto = (ActorDto) o;
        } else {
            return false;
        }

        if (actorDto.getId() != null) {
            return actorDto.getId().equals(id);
        }

        return actorDto.getName().equals(name);
    }

    @Override
    public int hashCode() {
        return id!=null?id:99999;
    }

}