package org.mouthaan.netify.service.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The class Bug Data Transfer Object.
 * Constructors, getters and setters are generated by Lombok
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class BugDto {
    private String bugKey;
    private String bugLocation;
    private Boolean bugEnabled;
    private Integer bugGroup;
    private String bugDescription;
}
