package org.mouthaan.netify.service.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * The class Genre Data Transfer Object.
 * Constructors, getters and setters are generated by Lombok
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class GenreDto {
    private Integer id;

    @NotNull(message = "genre.Dto.name.notnull")
    @Size(min = 3, max = 255, message = "genre.Dto.name.size")
    private String name;

    @Override
    public boolean equals(Object o) {
        GenreDto genreDto;
        if (o.getClass() == this.getClass()) {
            genreDto = (GenreDto) o;
        } else {
            return false;
        }

        if (genreDto.getId() != null) {
            return genreDto.getId().equals(id);
        }

        return genreDto.getName().equals(name);
    }

    @Override
    public int hashCode() {
        return id!=null?id:99999;
    }

}
