package org.mouthaan.netify.service.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The class Message Data Transfer Object.
 * Constructors, getters and setters are generated by Lombok
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
//@ApiModel(value = "Message", description = "A message containing more info why the operation failed")
public class MessageDto {
//    @ApiModelProperty(value = "Type of the message", readOnly = true)
    private String messageType;
//    @ApiModelProperty(value = "The message itself", readOnly = true)
    private String messageDescription;
}
