package org.mouthaan.netify.domain.model;


import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * The class Bug Entity.
 * Constructors, getters and setters are generated by Lombok
 */
@Entity
@Table(name = "ntfy_bug")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Bug implements Serializable {

    @Id
    @Column(name = "bug_key")
    @ApiModelProperty(notes = "The bug key")
    private String bugKey;

    @Column(name = "bug_location")
    @ApiModelProperty(notes = "The interface where the bug is located")
    private String bugLocation;

    @Column(name = "bug_enabled")
    @ApiModelProperty(notes = "The bug enabled")
    private Boolean bugEnabled;

    @Column(name = "bug_group")
    @ApiModelProperty(notes = "The bug group")
    private Integer bugGroup;

    @Column(name = "bug_description")
    @ApiModelProperty(notes = "The bug description")
    private String bugDescription;
}
